[tool.poetry]
name = "effective_python"
version = "0.1.0"
description = ""
authors = ["Krzysztof Misztal"]

[tool.poetry.dependencies]
python = "^3.7"
jupyter = "^1.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
